### ISSUE TITLE
Crash in Thor Room in St. Francis Folly

### ISSUE THREAD

**Issue by ANoDE85** [stohrendorf/EdisonEngine#194] opened 2021-12-12 14:45 UTC
Engine Version: Beta 7.1

Observed Behaviour:
Game crashed without error message after repeatedly re-loading the game and trying to not get hit by lightnings.
Please find the error log attached.
[edisonengine.log](https://github.com/stohrendorf/EdisonEngine/files/7698927/edisonengine.log)

**Comment by stohrendorf** [comment] 2021-12-12 21:38
unfortunately that log is mostly useless, the only interesting thing is
```
[2021-12-12 15:41:09.994515 info 0x000028b8] Swapping rooms
[2021-12-12 15:41:10.665098 info 0x000028b8] Swapping rooms
[2021-12-12 15:41:10.933093 debug 0x000028b8] 2 voices registered
[2021-12-12 15:41:10.961824 error 0x000028b8] Expectation failed at D:\EdisonEngine\3rdparty\gsl-lite-0.39.0\include\gsl/gsl-lite.hpp:2515
[2021-12-12 15:41:10.977731 error 0x000028b8]   - expression data_.ptr_ != nullptr
[2021-12-12 15:41:10.987112 error 0x000028b8]   - message GSL: Precondition failure
```
and that's not much, by far not enough to say more than "something's broken"

**Comment by stohrendorf** [comment] 2022-01-27 22:09
closing this because it can't be reproduced

**Closed by stohrendorf** 2022-01-27 22:09 UTC
Labels: bug
